---
- hosts: all
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: yes

  tasks:

  - name: Create superuser.
    user: name="{{ lookup('file', 'credentials/' + nickname + '/super_user_name') }}" 
          password="{{ lookup('file', 'credentials/' + nickname + '/super_user_password_crypted') }}" state=present
          groups="sudo"
          shell="/bin/bash"

  - name: Add authorized key.
    authorized_key: user="{{ lookup('file', 'credentials/' + nickname + '/super_user_name') }}" 
                    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: SSH configuration file update.
    template: src="files/conf/sshd_config.j2" dest="/etc/ssh/sshd_config" backup=yes owner=0 group=0 mode=0644
    notify: restart ssh

  - name: Set localtime to {{ timezone }}
    shell: "/bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime"

  - name: Set timezone to {{ timezone }}
    template: src="files/conf/timezone.j2" dest="/etc/timezone"
    notify: update tzdata

  handlers:
    - name: Update tzdata
      shell: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

    - include: handlers.yml
