---
- hosts: all
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: True

  tasks:
  - name: Update server packages.
    apt: update_cache=yes cache_valid_time=3600

  - name: Upgrade server packages.
    apt: upgrade=full

  handlers:
    - include: handlers.yml
